version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Budapest"
    open-pull-requests-limit: 5
    reviewers:
      - "jodajoda"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      # Group Vite and related build tools
      vite:
        patterns:
          - "vite*"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"
      # Group React dependencies
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-router*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      # Group dev dependencies
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      # Group Playwright
      playwright:
        patterns:
          - "@playwright/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Ignore major version updates (require manual review)
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "jodajoda"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
